### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by chairmantheboring**
I said I'd do it, even if it was a waste of time.

### CODE REVIEW

**Review by Vendicated — APPROVED** [review]
LGTM!!!

**Comment by Vendicated** [comment]
Could you document these changes? It's a bit hard to digest

**Review by Vendicated — CHANGES_REQUESTED** [review]
h

**Comment by chairmantheboring** [comment]
> Could you document these changes? It's a bit hard to digest

Absolutely!

**Comment by chairmantheboring** [comment]
Oops, wrong button!

**Comment by Vendicated** [comment]
LOL

**Review by Vendicated — APPROVED** [review]

**Comment by Vendicated** [comment]
wonderful! Gonna merge as soon as all the tests passed 😊👏🎉

**Pull request merged**
